//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_filmes
    {
        public int id_filme { get; set; }
        public string nome_filme { get; set; }
        public string genero_filme { get; set; }
        public string prod_filme { get; set; }
        public Nullable<System.DateTime> ano_filme { get; set; }
    }
}
